INSERT INTO faktor_penilaian(id_aspek,nama_kriteria,faktor,nilai)
VALUES
(1,'Common Sense','Secondary Factor',3),
(1,'Verbalisasi Ide','Secondary Factor',3),
(1,'Sistematika Berpikir','Core Factor',4),
(1,'Penalaran dan Solusi Real','Core Factor',4),
(1,'Konsentrasi','Secondary Factor',3),
(1,'Logika Praktis','Core Factor',4),
(1,'Fleksibilitas Berpikir','Core Factor',4),
(1,'Imajinasi Kreatif','Core Factor',5),
(1,'Antisipasi','Secondary Factor',3),
(1,'Potensi Kecerdasan','Core Factor',4),
(2,'Energi Psikis','Secondary Factor',3),
(2,'Ketelitian dan tanggung jawab','Core Factor',4),
(2,'Kehati-hatian','Secondary Factor',2),
(2,'Pengendalian Perasaan','Secondary Factor',3),
(2,'Dorongan Berprestasi','Secondary Factor',3),
(2,'Vitalitas dan Perencanaan','Core Factor',5),
(3,'Dominance (Kekuasaan)','Secondary Factor',3),
(3,'Influences (Pengaruh)','Secondary Factor',3),
(3,'Steadiness (Keteguhan Hati)','Core Factor',4),
(3,'Compliance (Pemenuhan)','Core Factor',5);